on:
  release:
    types: [published]

jobs:
  release-to-discord:
    runs-on: ubuntu-latest
    steps:
      - name: send-webhook
        id: discord
        uses: NatroTeam/discord-release-action@v1.0
        with:
          webhook_url: ${{secrets.WEBHOOK_URL}}
